// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sati.Data;

#nullable disable

namespace Sati.Migrations
{
    [DbContext(typeof(SatiContext))]
    [Migration("20260409130740_AddSupervisorHeirarchy")]
    partial class AddSupervisorHeirarchy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sati.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("Sati.Models.Incentive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DaysScheduled")
                        .HasColumnType("int");

                    b.Property<string>("ExcludedDatesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<decimal>("PerUnitIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Month", "Year")
                        .IsUnique();

                    b.ToTable("Incentives");
                });

            modelBuilder.Entity("Sati.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FormType")
                        .HasColumnType("int");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoteType")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Sati.Models.Scratchpad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Scratchpad");
                });

            modelBuilder.Entity("Sati.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbandonedAfterDays")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompAssessmentDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("CompAssessmentOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<string>("ContactTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentationTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ExcludeChristmas")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeDayAfterThanksgiving")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeIndependenceDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeIndigenousPeoplesDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeJuneteenth")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeLaborDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeMLKDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeMemorialDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeNewYearsDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludePresidentsDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeThanksgiving")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeVeteransDay")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeWednesday")
                        .HasColumnType("bit");

                    b.Property<int>("PcpDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("PcpOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<decimal>("PerUnitIncentive")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrivacyPracticesDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("PrivacyPracticesOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ProductivityThreshold")
                        .HasColumnType("int");

                    b.Property<int>("ReclassificationDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReclassificationOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseAgencyDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseAgencyOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseDhhsDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseDhhsOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseMedicalDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseMedicalOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("ReviewDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("ReviewOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<int>("SafetyPlanDaysAfterDue")
                        .HasColumnType("int");

                    b.Property<int>("SafetyPlanOpenDaysBefore")
                        .HasColumnType("int");

                    b.Property<string>("VisitTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Sati.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sati.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Waiver")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Sati.Models.Form", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany("Forms")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.Incentive", b =>
                {
                    b.HasOne("Sati.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sati.Models.Note", b =>
                {
                    b.HasOne("Sati.Person", "Person")
                        .WithMany("Notes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sati.Models.User", b =>
                {
                    b.HasOne("Sati.Models.User", "Supervisor")
                        .WithMany("Supervisees")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Sati.Person", b =>
                {
                    b.HasOne("Sati.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sati.Models.User", b =>
                {
                    b.Navigation("Supervisees");
                });

            modelBuilder.Entity("Sati.Person", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
